### ISSUE TITLE
[Bug]: Extended Mushrooms is tagging mushroom cap blocks as minecraft:wool

### ISSUE THREAD

**Issue by TelepathicGrunt** [cech12/ExtendedMushrooms#66]
### Minecraft Version

1.19.2

### Forge Version

43.1.52

### Mod Version

3.0.1.3

### Modpack or other Mod

Extended Mushrooms alone. (Can use mods that show tags on items if needed) Otherwise, use F3 while looking at Extended Mushroom's blocks

### Describe the Issue

It appears that Extended Mushrooms is tagging mushroom caps under the forge namespace into the minecraft:wool tag. This is not good because many mods relies upon the wool tag actually having wool. Not Mushroom caps. This will lead to wool based recipes that check that tag now can be crafted with Extended Mushroom's Honey Fungus Cap and other strange behaviors. My mod Bumblezone can take wool to repair an armor it has but now this block is also a valid ingredient due to this tag and my Bee Queen will trade wool for the honey mushroom cap which I do not want.

![image](https://user-images.githubusercontent.com/40846040/202918563-7b78f6d2-d346-4547-aa0c-e36f4c5c1239.png)

![image](https://user-images.githubusercontent.com/40846040/202918546-fe7fd8ed-5220-4552-bbef-32f2c46f01b2.png)

**Comment by cech12** [comment]
Hey! It is intended that the mushroom cap blocks are tagged as wool. I will not change that.

When you do not want that, you can override the wool tag in yoir mod pack. :)

**Comment by TelepathicGrunt** [comment]
May I ask why? Like what is the specific functionality you’re trying to do with this tag? 

Mainly because I’m not making a modpack. I’m a mod developer of Bumblezone mod and seeing your non-wool blocks as valid for my armor’s repair recipe and trading system is entirely unexpected and will also negatively affect other mods as well. Tags are meant to be use only when the block or item actually makes sense to be in it. 

And this is not really something that can easily be datapacked out by player too. It’s very easy to *add* a new entry to a tag. It’s much more difficult to remove an entry. Because tags are additive, a player setting replace to true in their own tag means they now have to hunt for all wool blocks in their modpack and manually define each one just to remove your tag entry which is bad player experience. 

I think it would be better for both your mod and other mods to not tag the mushroom caps as wool. And instead, use events or mixins to get whatever original tag functionality you wanted with your item

**Comment by TelepathicGrunt** [comment]
Last message I’ll make. Looking at the item tag wool on the wiki, the only functionality that I could see you trying for with the wool tag is the vibration damping but you can just put your items into that dampens vibration tag instead of the wool tag. It would also solve the bug where the paintings recipe unlocks happens when collecting a mushroom cap and vanilla paintings being craftable with mushroom cap in place of wool
https://minecraft.fandom.com/wiki/Tag

![C702701B-CA48-4E1A-8764-B6BF435C2B2D](https://user-images.githubusercontent.com/40846040/202920289-929152cb-ab1a-4b51-b245-403427b1d564.jpeg)

**Comment by cech12** [comment]
Thanks for your research and sharing your findings. All listed "bugs" are features that are intended by this mod. 

My mod adds a mushroom sheep (Baahshroom) that is generating mushroom cap blocks instead of wool. My mod adds recipes for wool carpets and beds which are using the mushroom cap blocks. So, when Extended Mushrooms is installed, all mushroom cap can be used as wool.

To enable this functionality in compatibility with other mods, the mushroom cap blocks are added to the vanilla wool tag. And as far as I can see, the intended behaviour affects also your mod. :)

If a mod pack developer or player adds your mod and my mod and do not want to use the mushroom caps as wool, which is not intended by my mod, she or he can change the wool tag. (the search funktionality of JEI is really good and all blocks tagged as wool can be found easily there.)

I think the player experience is much more bad when the mushroom caps must be added to the wool tag by each player, which is playing a modpack with no issues with mushroom caps tagged as wool.

**Comment by TelepathicGrunt** [comment]
Hmm, wouldn't that make more sense in that you created a non-wool-resource mushroom sheep than to reimagine mushroom caps as wool? It would be like saying diamond and iron ingots are honey items and can craft honey based stuff because Resourceful Bees's diamond and iron bees can produce them. Kinda weird. Except, Resourceful Bees view their bees as non-honey based and call it an ore-based bee instead of trying to redefine what the existing resource itself is. Just a different way of looking at this that might make more sense to a player considering how other mods works with re-used vanilla animals producing unique resources.

**Comment by cech12** [comment]
That is not the intention of my mod.
